version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - web

  - package-ecosystem: "npm"
    directory: "/apps/desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - desktop

  - package-ecosystem: "gomod"
    directory: "/apps/core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - go

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - dependencies
      - github-actions
